lints.workspace = true

[package]
name = "gix-quote"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing with various quotations used by git"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-workspace=true
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
gix-utils = { workspace=true }

bstr = { workspace=true, features = ["std"] }
thiserror = "2.0.17"
