lints.workspace = true

[package]
name = "gix-config-value"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project providing git-config value parsing"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-workspace=true
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "bstr/serde"]

[dependencies]
gix-path = { workspace=true }

thiserror = "2.0.17"
bstr = { workspace=true, features = ["std"] }
serde = { workspace=true, optional = true, features = ["derive"] }
bitflags = "2"

document-features = { workspace=true, optional = true }

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
