lints.workspace = true

[package]
name = "gix-blame"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dedicated to implementing a 'blame' algorithm"
authors = ["Christoph Rüßler <christoph.ruessler@mailbox.org>", "Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-workspace=true

[dependencies]
gix-commitgraph = { workspace=true }
gix-revwalk = { workspace=true }
gix-trace = { workspace=true }
gix-date = { workspace=true }
gix-diff = { workspace=true, features = ["blob"] }
gix-object = { workspace=true }
gix-hash = { workspace=true }
gix-worktree = { workspace=true, features = ["attributes"] }
gix-traverse = { workspace=true }

imara-diff = { path = "../../imara-diff" }

smallvec = { workspace = true }
thiserror = "2.0.17"

[dev-dependencies]
gix-ref = { workspace=true }
gix-filter = { workspace=true }
gix-fs = { workspace=true }
gix-index = { workspace=true }
gix-odb = { workspace=true }
gix-testtools = { workspace=true }
pretty_assertions = "1.4.0"
