lints.workspace = true

[package]
name = "gix-protocol"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project for implementing git protocols"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "!**/tests/**/*"]
rust-workspace=true

[lib]
doctest = false

[features]

#! ### _Mutually exclusive client _
#! The _client_ portion of the protocol uses `gix-transport` to communicate to a server. For it to be available, one of the following features must
#! be selected.
#!
#! Specifying both causes a compile error, preventing the use of `--all-features`.

## If set, blocking command implementations are available and will use the blocking version of the `gix-transport` crate.
blocking-client = [
    "gix-transport/blocking-client",
    "maybe-async/is_sync",
    "handshake",
    "fetch"
]
## As above, but provides async implementations instead.
# no `dep:` for futures-lite (https://github.com/rust-secure-code/cargo-auditable/issues/124)
async-client = [
    "gix-transport/async-client",
    "dep:async-trait",
    "dep:futures-io",
    "futures-lite",
    "handshake",
    "fetch"
]

## Add implementations for performing a `handshake` along with the dependencies needed for it.
handshake = ["dep:gix-credentials"]

## Add implementations for performing a `fetch` (for packs) along with the dependencies needed for it.
fetch = [
    "dep:gix-negotiate",
    "dep:gix-object",
    "dep:gix-revwalk",
    "dep:gix-lock",
    "dep:gix-refspec",
    "dep:gix-trace",
]

#! ### Other
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "bstr/serde", "gix-transport/serde", "gix-hash/serde", "gix-shallow/serde"]

[[test]]
name = "blocking"

required-features = ["blocking-client"]

[[test]]
name = "async"

required-features = ["async-client"]

[dependencies]
gix-features = { workspace=true, features = [
    "progress",
] }
gix-transport = { workspace=true }
gix-hash = { workspace=true }
gix-shallow = { workspace=true }
gix-date = { workspace=true }
gix-utils = { workspace=true }
gix-ref = { workspace=true }

gix-trace = { workspace=true, optional = true }
gix-negotiate = { workspace=true, optional = true }
gix-object = { workspace=true, optional = true }
gix-revwalk = { workspace=true, optional = true }
gix-credentials = { workspace=true, optional = true }
gix-refspec = { workspace=true, optional = true }
gix-lock = { workspace=true, optional = true }

thiserror = "2.0.17"
serde = { workspace=true, optional = true, features = [
    "derive",
] }
bstr = { workspace=true, features = [
    "std",
    "unicode",
] }
winnow = { workspace=true, features = ["simd"] }

# for async-client
async-trait = { workspace=true, optional = true }
futures-io = { workspace=true, optional = true }
futures-lite = { workspace=true, optional = true }
maybe-async = "0.2.6"

document-features = { workspace=true, optional = true }

[dev-dependencies]
async-std = { workspace=true, features = ["attributes"] }
gix-packetline = {workspace=true }

[package.metadata.docs.rs]
features = ["blocking-client", "document-features", "serde"]
