lints.workspace = true

[package]
name = "gix-actor"
#workspace=true
description = "A way to identify git actors"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-workspace=true

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "bstr/serde", "gix-date/serde"]

[dependencies]
gix-date = { workspace=true }
gix-utils = { workspace=true }

thiserror = "2.0.17"
bstr = { workspace=true, features = [
    "std",
    "unicode",
] }
winnow = { workspace=true, features = ["simd"] }
itoa = "1.0.1"
serde = { workspace=true, optional = true, features = [
    "derive",
] }

document-features = { workspace=true, optional = true }

[dev-dependencies]
pretty_assertions = "1.0.0"
gix-testtools = {  workspace=true}
gix-hash = {  workspace=true}

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
