lints.workspace = true

[package]
name = "gix-prompt"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project for handling prompts in the terminal"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "README.md"]
rust-workspace=true

[lib]
doctest = false

[dependencies]
gix-command = { workspace=true }
gix-config-value = { workspace=true }

thiserror = "2.0.17"

[target.'cfg(unix)'.dependencies]
rustix = { workspace=true, features = ["termios"] }
#parking_lot = "0.12.4"
parking_lot = {workspace=true}

[dev-dependencies]
gix-testtools = { workspace=true }
serial_test = { workspace=true }

[target.'cfg(any(target_os = "linux", target_os = "freebsd", target_os = "macos"))'.dev-dependencies]
expectrl = "0.7.0"
