lints.workspace = true

[package]
name = "gix-config"

repository = "https://github.com/GitoxideLabs/gitoxide"
description = "A git-config file parser and editor from the gitoxide project"
license = "MIT OR Apache-2.0"
authors = ["Edward Shen <code@eddie.sh>"]
edition = "2021"
keywords = ["git-config", "git", "config", "gitoxide"]
categories = ["config", "parser-implementations"]
include = ["src/**/*", "LICENSE-*", "README.md"]
rust-workspace=true
autotests = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "bstr/serde", "gix-sec/serde", "gix-ref/serde", "gix-glob/serde", "gix-config-value/serde"]

[dependencies]
gix-features = { workspace=true }
gix-config-value = { workspace=true }
gix-path = { workspace=true }
gix-sec = { workspace=true }
gix-ref = { workspace=true }
gix-glob = { workspace=true }

winnow = { workspace=true, features = ["simd"] }
memchr = "2"
thiserror = "2.0.17"
unicode-bom = { workspace=true }
bstr = { workspace=true, features = ["std"] }
serde = { workspace=true, optional = true, features = ["derive"] }
smallvec = { workspace = true }

document-features = { workspace=true, optional = true }

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "large_config_file"
harness = false


[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
