lints.workspace = true

[package]
name = "gix-revision"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing with finding names for revisions and parsing specifications"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "README.md"]
rust-workspace=true

[lib]
doctest = false

[features]
default = ["describe", "merge_base"]

## `git describe` functionality
describe = ["dep:gix-trace", "dep:gix-hashtable"]

## `git merge-base` functionality
merge_base = ["dep:gix-trace", "dep:bitflags"]

## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "gix-hash/serde", "gix-object/serde"]

[dependencies]
gix-hash = { workspace=true }
gix-object = { workspace=true }
gix-date = { workspace=true }
gix-hashtable = { workspace=true, optional = true }
gix-revwalk = { workspace=true }
gix-commitgraph = { workspace=true }
gix-trace = { workspace=true, optional = true }

bstr = { workspace=true, features = ["std"] }
bitflags = { workspace=true, optional = true }
thiserror = "2.0.17"
serde = { workspace=true, optional = true, features = ["derive"] }
document-features = { workspace=true, optional = true }

[dev-dependencies]
gix-odb = { workspace=true }
gix-testtools = { workspace=true }
permutohedron = "0.2.4"

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
