lints.workspace = true

[package]
name = "gix-shallow"

repository = "https://github.com/GitoxideLabs/gitoxide"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
license = "MIT OR Apache-2.0"
description = "Handle files specifying the shallow boundary"
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-workspace=true

[lib]
doctest = false
test = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "gix-hash/serde"]

[dependencies]
gix-hash = { workspace=true }
gix-lock = { workspace=true }

thiserror = "2.0.17"
bstr = { workspace=true }
serde = { workspace=true, optional = true, features = ["std", "derive"] }
