lints.workspace = true

[package]
name = "gitoxide-core"
description = "The library implementing all capabilities of the gitoxide CLI"
repository = "https://github.com/GitoxideLabs/gitoxide"

authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
doctest = false
test = false

[features]
default = []

#! ### Tools
## Discover all git repositories within a directory. Particularly useful with [skim](https://github.com/lotabout/skim).
organize = ["dep:gix-url", "dep:jwalk"]
## Derive the amount of time invested into a git repository akin to [git-hours](https://github.com/kimmobrunfeldt/git-hours).
estimate-hours = ["dep:fs-err", "dep:crossbeam-channel", "dep:smallvec"]
## Gather information about repositories and store it in a database for easy querying.
query = ["dep:rusqlite"]
## Run algorithms on a corpus of repositories and store their results for later comparison and intelligence gathering.
## *Note that* `organize` we need for finding git repositories fast.
corpus = ["dep:rusqlite", "dep:sysinfo", "organize", "dep:crossbeam-channel", "dep:serde_json", "dep:tracing-forest", "dep:tracing-subscriber", "tracing", "dep:parking_lot"]

## The ability to create archives from virtual worktrees, similar to `git archive`.
archive = ["dep:gix-archive-for-configuration-only", "gix/worktree-archive"]

## The ability to clean a repository, similar to `git clean`.
clean = ["gix/dirwalk"]

#! ### Mutually Exclusive Networking
#! If both are set, _blocking-client_ will take precedence, allowing `--all-features` to be used.

## If set, the client used to connect to git servers will use a blocking API. It supports more transports and is what most would want.
blocking-client = ["gix/blocking-network-client"]
## The client to connect to git servers will be async, while supporting only the 'git' transport itself.
## It's the most limited and can be seen as example on how to use custom transports for custom servers.
async-client = ["gix/async-network-client-async-std", "gix-transport-configuration-only/async-std", "async-trait", "futures-io", "async-net", "async-io", "futures-lite", "blocking"]

#! ### Other
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["gix/serde", "dep:serde_json", "dep:serde", "bytesize/serde"]


[dependencies]
# deselect everything else (like "performance") as this should be controllable by the parent application.
gix = { workspace=true, features = ["merge", "blob-diff", "blame", "revision", "mailmap", "excludes", "attributes", "worktree-mutation", "credentials", "interrupt", "status", "dirwalk"] }
gix-pack-for-configuration-only = { package = "gix-pack", workspace=true, features = ["pack-cache-lru-dynamic", "pack-cache-lru-static", "generate", "streaming-input"] }
gix-transport-configuration-only = { package = "gix-transport", workspace=true }
gix-archive-for-configuration-only = { package = "gix-archive", workspace=true, optional = true, features = ["tar", "tar_gz"] }
gix-status = { workspace=true }
gix-fsck = { workspace=true }
serde = { workspace=true, optional = true, features = ["derive"] }
anyhow = "1.0.100"
thiserror = "2.0.17"
bytesize = "2.3.1"
tempfile = "3.23.0"

# for async-client
async-trait = { workspace=true, optional = true }
async-net = { workspace=true, optional = true }
futures-lite = { workspace=true, optional = true }
async-io = { workspace=true, optional = true }
futures-io = { workspace=true, optional = true }
blocking = { workspace=true, optional = true }

# for 'organize' functionality
gix-url = { workspace=true, optional = true }
jwalk = { workspace=true, optional = true }

# for 'hours'
fs-err = { workspace=true, optional = true }
crossbeam-channel = { workspace=true, optional = true }
smallvec = { workspace=true, optional = true }

# for 'query' and 'corpus'
rusqlite = { workspace=true, optional = true, features = ["bundled"] }

# for 'corpus'
parking_lot = { workspace=true, optional = true }
sysinfo = { workspace=true, optional = true, features = ["system"] }
serde_json = { workspace=true, optional = true }
tracing-forest = { workspace=true, features = ["serde"], optional = true }
tracing-subscriber = { workspace=true, optional = true }
tracing = { workspace=true, optional = true }

# for svg graph output
layout-rs = "0.1.3"
open = "5.0.0"

document-features = { workspace=true, optional = true }

[package.metadata.docs.rs]
features = ["document-features", "blocking-client", "organize", "estimate-hours", "serde"]
