lints.workspace = true

[package]
name = "gix-testtools"
description = "Shared code for gitoxide crates to facilitate testing"

authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
include = ["/src/**/*", "/LICENSE-*"]
rust-workspace=true

#[[bin]]
#name = "jtt"


[lib]
doctest = false

[features]
default = []
## Use instead of plain `tar` files, compress these to produce `tar.xz` files instead.
## This is useful if archives are uploaded into `git-lfs`, which doesn't have built-in compression
## and metering counts towards uncompressed bytes transferred.
xz = ["dep:xz2"]

[dependencies]
gix-lock = { workspace=true }
gix-discover = { workspace=true }
gix-worktree = { workspace=true }
gix-fs = { workspace=true }
gix-tempfile = { workspace=true, features = ["signals"] }

winnow = { workspace=true, features = ["simd"] }
fastrand = "2.0.0"
bstr = { workspace=true }
crc = "3.4.0"
tempfile = "3.23.0"
fs_extra = "1.2.0"
parking_lot = { workspace=true }
is_ci = "1.1.1"
io-close = "0.3.7"
tar = { workspace=true }
xz2 = { workspace=true, optional = true }

document-features = { workspace=true, optional = true }

[dev-dependencies]
serial_test = { workspace=true }

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
