lints.workspace = true

[package]
name = "gix-status"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing with 'git status'-like functionality"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>", "Pascal Kuthe <pascal.kuthe@semimod.de>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-workspace=true
autotests = false

[lib]
doctest = false

[features]
## Add support for tracking rewrites along with checking for worktree modifications.
worktree-rewrites = ["dep:gix-dir", "dep:gix-diff"]

[dependencies]
gix-index = { workspace=true }
gix-fs = { workspace=true }
gix-hash = { workspace=true }
gix-object = { workspace=true }
gix-path = { workspace=true }
gix-features = { workspace=true, features = ["progress"] }
gix-filter = { workspace=true }
gix-worktree = { workspace=true, features = ["attributes"] }
gix-pathspec = { workspace=true }

gix-dir = { workspace=true, optional = true }
gix-diff = { workspace=true, features = ["blob"], optional = true }

thiserror = "2.0.17"
filetime = "0.2.15"
bstr = { workspace=true }

document-features = { workspace=true, optional = true }

[target.'cfg(not(target_has_atomic = "64"))'.dependencies]
portable-atomic = "1"

[package.metadata.docs.rs]
features = ["document-features", "worktree-rewrites"]
