lints.workspace = true

[package]
name = "gix-odb"
#workspace=true
repository = "https://github.com/GitoxideLabs/gitoxide"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
license = "MIT OR Apache-2.0"
description = "Implements various git object databases"
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-workspace=true
autotests = false

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "gix-hash/serde", "gix-object/serde", "gix-pack/serde"]

[dependencies]
gix-features = { workspace=true, features = ["walkdir", "zlib", "crc32"] }
gix-hashtable = { workspace=true }
gix-hash = { workspace=true }
gix-date = { workspace=true }
gix-path = { workspace=true }
gix-quote = { workspace=true }
gix-object = { workspace=true }
gix-pack = { workspace=true }
gix-fs = { workspace=true }
serde = { workspace=true, optional = true, features = ["derive"] }

tempfile = "3.23.0"
thiserror = "2.0.17"
parking_lot = { workspace=true }
arc-swap = "1.5.0"

document-features = { workspace=true, optional = true }

[package.metadata.docs.rs]
features = ["document-features", "serde"]
