lints.workspace = true

[package]
name = "gix-pathspec"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing magical pathspecs"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-workspace=true
include = ["src/**/*", "LICENSE-*", "README.md"]

[lib]
doctest = false

[dependencies]
gix-glob = { workspace=true }
gix-path = { workspace=true }
gix-attributes = { workspace=true }
gix-config-value = { workspace=true }

bstr = { workspace=true, features = ["std"] }
bitflags = "2"
thiserror = "2.0.17"

[dev-dependencies]
gix-testtools = { workspace=true }
#serial_test = "3.1.1"
serial_test = {workspace=true}
