lints.workspace = true

[package]
name = "gix-hashtable"
#workspace=true
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate that provides hashtable based data structures optimized to utilize ObjectId keys"
authors = ["Pascal Kuthe <pascal.kuthe@semimod.de>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-workspace=true

[lib]
doctest = false

[dependencies]
#parking_lot = "0.12.4"
parking_lot = {workspace=true}
hashbrown = { workspace=true, features = ["inline-more"] }
gix-hash = { workspace=true }
