lints.workspace = true

[package]
name = "gix-negotiate"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project implementing negotiation algorithms"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-workspace=true
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false
test = false

[dependencies]
gix-hash = { workspace=true }
gix-object = { workspace=true }
gix-date = { workspace=true }
gix-commitgraph = { workspace=true }
gix-revwalk = { workspace=true }
thiserror = "2.0.17"
smallvec = { workspace = true }
bitflags = "2"

[dev-dependencies]
gix-testtools = { workspace=true }
gix-odb = {  }
gix-ref = {  }
