lints.workspace = true

[package]
name = "gix-submodule"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing git submodules"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-workspace=true
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
gix-pathspec = { workspace=true }
gix-refspec = { workspace=true }
gix-config = { workspace=true }
gix-path = { workspace=true }
gix-url = { workspace=true }

bstr = { workspace=true }
thiserror = "2.0.17"

[dev-dependencies]
gix-testtools = { workspace=true }
gix-features = { workspace = true, features = ["walkdir"] }
