lints.workspace = true

[package]
name = "gix-traverse-tests"
workspace=true
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "Integration tests for the gix-traverse crate"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-workspace=true

[[test]]
name = "traverse"


[dev-dependencies]
insta = "1.44.3"
gix-traverse = {  }
gix-testtools = {  }
gix-odb = {  }
gix-hash = {  }
gix-object = {  }
gix-commitgraph = {  }
gix-path = { workspace=true }
