lints.workspace = true

[package]
name = "gix-credentials"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project to interact with git credentials helpers"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-workspace=true
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "bstr/serde", "gix-sec/serde"]

[dependencies]
gix-sec = { workspace=true }
gix-url = { workspace=true }
gix-path = { workspace=true }
gix-command = { workspace=true }
gix-config-value = { workspace=true }
gix-prompt = { workspace=true }
gix-date = { workspace=true }
gix-trace = { workspace=true }

thiserror = "2.0.17"
serde = { workspace=true, optional = true, features = ["derive"] }
bstr = { workspace=true, features = ["std"] }
document-features = { workspace=true, optional = true }

[dev-dependencies]
gix-testtools = { workspace=true }


[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
