lints.workspace = true

[package]
name = "gix-archive"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "archive generation from of a worktree stream"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-workspace=true
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[features]
default = ["tar", "tar_gz", "zip"]

## Enable the `tar` archive format. It has support for all information, except for object ids.
tar = ["dep:tar", "dep:gix-path"]
## Enable the `tar.gz` archive format.
tar_gz = ["tar", "dep:flate2"]

## Enable the `zip` archive format.
zip = ["dep:zip"]


[dependencies]
gix-worktree-stream = { workspace=true }
gix-object = { workspace=true }
gix-path = { workspace=true, optional = true }
gix-date = { workspace=true }

flate2 = { workspace=true, optional = true, features = ["zlib-rs"] }
zip = { workspace=true, optional = true, features = ["deflate-flate2"] }
jiff = { workspace=true, features = ["std"] }

thiserror = "2.0.17"
bstr = { workspace=true }

tar = { workspace=true, optional = true }

document-features = { workspace=true, optional = true }

[dev-dependencies]
gix-testtools = { workspace=true }
gix-odb = {  }
gix-worktree = {features = [
    "attributes",
] }
gix-hash = {  }
gix-attributes = {  }
gix-object = {  }
gix-filter = {  }

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
