lints.workspace = true

[package]
name = "gix-traverse"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-workspace=true
autotests = false

[lib]
doctest = false

[dependencies]
gix-hash = { workspace=true }
gix-object = { workspace=true }
gix-date = { workspace=true }
gix-hashtable = { workspace=true }
gix-revwalk = { workspace=true }
gix-commitgraph = { workspace=true }
smallvec = { workspace = true }
thiserror = "2.0.17"
bitflags = "2"
