lints.workspace = true

[package]
name = "gix-tempfile"
#workspace=true
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A tempfile implementation with a global registry to assure cleanup"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "README.md"]
rust-workspace=true

[[example]]
name = "delete-tempfiles-on-sigterm"

required-features = ["signals"]

[[example]]
name = "delete-tempfiles-on-sigterm-interactive"

required-features = ["signals"]

[[example]]
name = "try-deadlock-on-cleanup"

required-features = ["signals"]

[lib]
doctest = false
test = true

[dependencies]
gix-fs = { workspace=true }
#parking_lot = "0.12.4"
parking_lot = {workspace=true}

dashmap = { workspace=true, optional = true }
tempfile = "3.23.0"

signal-hook = { workspace=true, optional = true }
signal-hook-registry = { workspace=true, optional = true }

document-features = { workspace=true, optional = true }

[features]
default = ["hp-hashmap"]
## Support for signal handlers to cleanup tempfiles when a signal is received.
signals = ["dep:signal-hook", "dep:signal-hook-registry"]
## Use a high-performance concurrent hashmap implementation for optimal performance with less contention if there are many tempfiles opening at the same time.
## It also allows to potentially cleanup more tempfiles in a signal handler as the hashmap can be partially locked.
hp-hashmap = ["dep:dashmap"]

[target.'cfg(not(windows))'.dependencies]
libc = { workspace=true }

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
