lints.workspace = true

[package]
name = "gix-worktree"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project for shared worktree related types and utilities."
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-workspace=true
autotests = false

[lib]
doctest = false

[features]
default = ["attributes"]
## Instantiate stacks that can access `.gitattributes` information.
attributes = ["dep:gix-attributes", "dep:gix-validate"]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "bstr/serde", "gix-index/serde", "gix-hash/serde", "gix-object/serde", "gix-attributes?/serde", "gix-ignore/serde"]

[dependencies]
gix-index = { workspace=true }
gix-fs = { workspace=true }
gix-hash = { workspace=true }
gix-object = { workspace=true }
gix-glob = { workspace=true }
gix-path = { workspace=true }
gix-attributes = { workspace=true, optional = true }
gix-validate = { workspace=true, optional = true }
gix-ignore = { workspace=true }
gix-features = { workspace=true }

serde = { workspace=true, optional = true, features = ["derive"] }
bstr = { workspace=true }

document-features = { workspace=true, optional = true }

[package.metadata.docs.rs]
features = ["document-features", "serde"]
