lints.workspace = true

[package]
name = "gix-pack"
#workspace=true
repository = "https://github.com/GitoxideLabs/gitoxide"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
license = "MIT OR Apache-2.0"
description = "Implements git packs and related data structures"
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-workspace=true
autotests = false

[lib]
doctest = false

[features]
default = ["generate", "streaming-input"]
## generate new packs from a set of objects.
generate = ["dep:gix-traverse", "dep:gix-diff", "dep:parking_lot", "dep:gix-hashtable"]
## Receive a pack as datastream and resolve it
streaming-input = ["dep:parking_lot", "dep:gix-tempfile"]
## Provide a fixed-size allocation-free LRU cache for packs. It's useful if caching is desired while keeping the memory footprint
## for the LRU-cache itself low.
pack-cache-lru-static = ["dep:uluru"]
## Provide a hash-map based LRU cache whose eviction is based a memory cap calculated from object data.
pack-cache-lru-dynamic = ["dep:clru"]
## If set, select algorithms may additionally use a full-object cache which is queried before the pack itself.
object-cache-dynamic = ["dep:clru", "dep:gix-hashtable"]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "gix-object/serde"]
## Make it possible to compile to the `wasm32-unknown-unknown` target.
wasm = ["gix-diff?/wasm"]

[dependencies]
gix-features = { workspace=true, features = ["crc32", "progress", "zlib"] }
gix-path = { workspace=true }
gix-hash = { workspace=true }
gix-chunk = { workspace=true }
gix-object = { workspace=true }
gix-hashtable = { workspace=true, optional = true }

# for streaming of packs (input, output)
gix-traverse = { workspace=true, optional = true }
gix-diff = { workspace=true, optional = true }

memmap2 = "0.9.7"
smallvec = { workspace = true }
parking_lot = { workspace=true, optional = true }
thiserror = "2.0.17"

# for caching
uluru = { workspace=true, optional = true }
clru = { workspace=true, optional = true }

serde = { workspace=true, optional = true, features = ["derive"] }
## If enabled, `cargo doc` will see feature documentation from this manifest.
document-features = { workspace=true, optional = true }


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
gix-tempfile = { workspace=true, optional = true }

[dev-dependencies]
gix-testtools = {  workspace=true}

[package.metadata.docs.rs]
all-features = true
features = ["document-features", "pack-cache-lru-dynamic", "object-cache-dynamic", "serde"]
