lints.workspace = true

[package]
name = "gix-index"
version = "0.42.1"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A work-in-progress crate of the gitoxide project dedicated implementing the git index file"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "README.md"]
# rust-version = "1.82"
autotests = false


[lib]
doctest = false
test = true

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = [
#"dep:serde",
"smallvec/serde", "gix-hash/serde"]

[dependencies]
gix-features.workspace = true #{ version.workspace = true #"^0.44.1", path.workspace = true #"../gix-features", features.workspace = true #[
#    "progress",
#] }
gix-hash.workspace = true #{ version.workspace = true #"^0.20.1", path.workspace = true #"../gix-hash" }
gix-bitmap.workspace = true #{ version.workspace = true #"^0.2.15", path.workspace = true #"../gix-bitmap" }
gix-object.workspace = true #{ version.workspace = true #"^0.51.1", path.workspace = true #"../gix-object" }
gix-validate.workspace = true #{ version.workspace = true #"^0.10.1", path.workspace = true #"../gix-validate" }
gix-traverse.workspace = true #{ version.workspace = true #"^0.48.0", path.workspace = true #"../gix-traverse" }
gix-lock.workspace = true #{ version.workspace = true #"^19.0.0", path.workspace = true #"../gix-lock" }
gix-fs.workspace = true #{ version.workspace = true #"^0.17.0", path.workspace = true #"../gix-fs" }
gix-utils.workspace = true #{ version.workspace = true #"^0.3.1", path.workspace = true #"../gix-utils" }
hashbrown.workspace = true #{ git.workspace = true #"https://github.com/meta-introspector/hashbrown", branch.workspace = true #"feature/CRQ-016-nixify" }
fnv.workspace = true #"1.0.7"
thiserror.workspace = true #"2.0.17"
memmap2.workspace = true #"0.9.7"
filetime.workspace = true #"0.2.15"
bstr.workspace = true #{ version.workspace = true #"1.12.0", default-features.workspace = true #false }
serde.workspace = true #{ version.workspace = true #"1.0.114", optional.workspace = true #true, default-features.workspace = true #false, features.workspace = true #[    "derive",] }
smallvec.workspace = true #"1.15.1"
itoa.workspace = true #"1.0.3"
bitflags.workspace = true #"2"

document-features.workspace = true #{ version = "0.2.0", optional = true }

[target.'cfg(not(windows))'.dependencies]
rustix = { version = "1.1.2", default-features = false, features = [
    "std",
    "fs",
] }
libc = { version = "0.2.176" }

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }

[package.metadata.docs.rs]
features = ["document-features", "serde"]
