lints.workspace = true

[package]
name = "gix-index"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A work-in-progress crate of the gitoxide project dedicated implementing the git index file"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "README.md"]
rust-workspace=true
autotests = false


[lib]
doctest = false
test = true

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "smallvec/serde", "gix-hash/serde"]

[dependencies]
gix-features = { workspace=true, features = [
    "progress",
] }
gix-hash = { workspace=true }
gix-bitmap = { workspace=true }
gix-object = { workspace=true }
gix-validate = { workspace=true }
gix-traverse = { workspace=true }
gix-lock = { workspace=true }
gix-fs = { workspace=true }
gix-utils = { workspace=true }

hashbrown = "0.16.0"
fnv = "1.0.7"
thiserror = "2.0.17"
memmap2 = "0.9.7"
filetime = "0.2.15"
bstr = { workspace=true }

serde = { workspace=true, optional = true, features = [
    "derive",
] }
smallvec = { workspace = true }
itoa = "1.0.3"
bitflags = "2"

document-features = { workspace=true, optional = true }

[target.'cfg(not(windows))'.dependencies]
rustix = { workspace=true, features = [
    "std",
    "fs",
] }
libc = { workspace=true }

[dev-dependencies]
gix-testtools = { workspace=true }

[package.metadata.docs.rs]
features = ["document-features", "serde"]
