lints.workspace = true

[package]
name = "gix-filter"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project implementing git filters"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-workspace=true
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
gix-hash = { workspace=true }
gix-trace = { workspace=true }
gix-object = { workspace=true }
gix-command = { workspace=true }
gix-quote = { workspace=true }
gix-utils = { workspace=true }
gix-path = { workspace=true }
gix-packetline = { workspace=true, features = ["blocking-io"] }
gix-attributes = { workspace=true }

encoding_rs = "0.8.32"
bstr = { workspace=true, features = ["std"] }
thiserror = "2.0.17"
smallvec = { workspace = true }


[dev-dependencies]
serial_test = { workspace=true }
gix-testtools = { workspace=true }
gix-worktree = {features = ["attributes"] , workspace=true}
