lints.workspace = true

[package]
name = "gix-hash"
#workspace=true
description = "Borrowed and owned git hash digests used to identify git objects"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-workspace=true

[lib]
doctest = false
test = false

[features]
default = ["sha1"]
## Support for SHA-1 digests.
sha1 = []
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "faster-hex/serde"]

[dependencies]
gix-features = { workspace=true, features = ["progress"] }

thiserror = "2.0.17"
faster-hex = { workspace=true, features = ["std"] }
serde = { workspace=true, optional = true, features = ["derive"] }
sha1-checked = { workspace=true }

document-features = { workspace=true, optional = true }

[dev-dependencies]
gix-testtools = { workspace=true }

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
