# [source.crates-io]


# [patch.crates-io]
# hashbrown = { git = "https://github.com/meta-introspector/hashbrown", branch = "feature/CRQ-016-nixify" }
# #rev = "061804bc"


# [source.vendored-sources]
# directory = "vendor"