lints.workspace = true

[package]
name = "gix-dir"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing with directory walks"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-workspace=true

[lib]
doctest = false
test = false

[dependencies]
gix-trace = { workspace=true }
gix-index = { workspace=true }
gix-discover = { workspace=true }
gix-fs = { workspace=true }
gix-path = { workspace=true }
gix-pathspec = { workspace=true }
gix-worktree = { workspace=true }
gix-object = { workspace=true }
gix-ignore = { workspace=true }
gix-utils = { workspace=true, features = ["bstr"] }

bstr = { workspace=true }
thiserror = "2.0.17"

[dev-dependencies]
gix-testtools = { workspace=true }
gix-fs = { workspace = true }
pretty_assertions = "1.4.0"
