lints.workspace = true

[package]
name = "gix-ref"
#workspace=true
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate to handle git references"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-workspace=true
autotests = false

[lib]
doctest = false
test = true

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "gix-hash/serde", "gix-actor/serde", "gix-object/serde"]

[dependencies]
gix-features = { workspace=true, features = ["walkdir"] }
gix-fs = { workspace=true }
gix-path = { workspace=true }
gix-hash = { workspace=true }
gix-object = { workspace=true }
gix-utils = { workspace=true }
gix-validate = { workspace=true }
gix-actor = { workspace=true }
gix-lock = { workspace=true }
gix-tempfile = { workspace=true }

thiserror = "2.0.17"
winnow = { workspace=true, features = ["simd"] }
serde = { workspace=true, optional = true, features = ["derive"] }

# packed refs
memmap2 = "0.9.7"

document-features = { workspace=true, optional = true }

[dev-dependencies]
gix-testtools = { workspace=true }
gix-date = { workspace=true }

[package.metadata.docs.rs]
features = ["document-features", "serde"]
