lints.workspace = true

[package]
name = "internal-tools"
description = "internal CLI tooling to help generated test-cases"
workspace=true
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
rust-workspace=true

[[bin]]
name = "it"


[dependencies]
anyhow = "1.0.100"
clap = { workspace=true, features = ["derive"] }
gix = { workspace=true, features = ["attributes", "blame", "blob-diff", "revision"] }
regex = { workspace=true, features = ["std"] }
