lints.workspace = true

[package]
name = "gix-commitgraph"

repository = "https://github.com/GitoxideLabs/gitoxide"
documentation = "https://git-scm.com/docs/commit-graph"
license = "MIT OR Apache-2.0"
description = "Read-only access to the git commitgraph file format"
authors = ["Conor Davis <gitoxide@conor.fastmail.fm>", "Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-workspace=true

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`
serde = ["dep:serde", "gix-hash/serde", "bstr/serde"]

[dependencies]
gix-hash = { workspace=true }
gix-chunk = { workspace=true }

bstr = { workspace=true, features = ["std"] }
memmap2 = "0.9.7"
serde = { workspace=true, optional = true, features = ["derive"] }
thiserror = "2.0.17"

document-features = { workspace=true, optional = true }

[dev-dependencies]
gix-testtools = { workspace=true }
gix-date = {  workspace=true}

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
