lints.workspace = true

[package]
name = "gix-fs"
#workspace=true
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate providing file system specific utilities to `gitoxide`"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-workspace=true
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde"]

[dependencies]
bstr = "1.12.0"
gix-path = { workspace=true }
gix-features = { workspace=true, features = ["fs-read-dir"] }
gix-utils = { workspace=true }
thiserror = "2.0.17"
serde = { workspace=true, optional = true, features = ["std", "derive"] }

# For `Capabilities` to assure parallel operation works.
fastrand = { workspace=true, features = ["std"] }

[dev-dependencies]
crossbeam-channel = "0.5.15"
is_ci = "1.1.1"
tempfile = "3.23.0"
