lints.workspace = true

[package]
name = "gix-command"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project handling internal git command execution"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-workspace=true
include = ["src/lib.rs", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
gix-trace = { workspace=true }
gix-path = { workspace=true }
gix-quote = { workspace=true }

bstr = { workspace=true, features = ["std", "unicode"] }
shell-words = "1.0"

[dev-dependencies]
gix-testtools = { workspace=true }
