lints.workspace = true

[package]
name = "gix-worktree-state"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project implementing setting the worktree to a particular state"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-workspace=true
autotests = false

[lib]
doctest = false

[dependencies]
gix-worktree = { workspace=true, features = ["attributes"] }
gix-index = { workspace=true }
gix-fs = { workspace=true }
gix-object = { workspace=true }
gix-path = { workspace=true }
gix-features = { workspace=true }
gix-filter = { workspace=true }

io-close = "0.3.7"
thiserror = "2.0.17"
bstr = { workspace=true }
