lints.workspace = true

[package]
name = "gix-worktree-stream"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "generate a byte-stream from a git-tree"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-workspace=true
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
gix-features = { workspace=true, features = ["progress", "io-pipe"] }
gix-hash = { workspace=true }
gix-object = { workspace=true }
gix-attributes = { workspace=true }
gix-filter = { workspace=true }
gix-traverse = { workspace=true }
gix-fs = { workspace=true }
gix-path = { workspace=true }

thiserror = "2.0.17"
#parking_lot = "0.12.4"
parking_lot = {workspace=true}

[dev-dependencies]
gix-testtools = { workspace=true }
gix-odb = {  }
gix-worktree = {features = ["attributes"] }
