[package]
name = "gix-merge"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project implementing merge algorithms"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-workspace=true

[lints]
workspace = true

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "gix-hash/serde", "gix-object/serde"]

[dependencies]
gix-hash = { workspace=true }
gix-object = { workspace=true }
gix-filter = { workspace=true }
gix-worktree = { workspace=true, features = ["attributes"] }
gix-command = { workspace=true }
gix-path = { workspace=true }
gix-fs = { workspace=true }
gix-tempfile = { workspace=true }
gix-trace = { workspace=true }
gix-quote = { workspace=true }
gix-revision = { workspace=true, features = ["merge_base"] }
gix-revwalk = { workspace=true }
gix-diff = { workspace=true, features = ["blob"] }
gix-index = { workspace=true }

thiserror = "2.0.17"
imara-diff = { workspace=true }
bstr = { workspace=true }
serde = { workspace=true, optional = true, features = ["derive"] }

document-features = { workspace=true, optional = true }

[dev-dependencies]
gix-testtools = { workspace=true }
gix-odb = { workspace=true }
gix-utils = { workspace=true }
termtree = "0.5.1"
pretty_assertions = "1.4.0"

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
