lints.workspace = true

[package]
name = "gix-refspec"

repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project for parsing and representing refspecs"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "README.md"]
rust-workspace=true

[lib]
doctest = false

[dependencies]
gix-revision = { workspace=true }
gix-validate = { workspace=true }
gix-hash = { workspace=true }
gix-glob = { workspace=true }

bstr = { workspace=true, features = ["std"] }
thiserror = "2.0.17"
smallvec = { workspace = true }

[dev-dependencies]
gix-testtools = { workspace=true }
insta = "1.44.3"
