lints.workspace = true

[package]
name = "gix-fsck"

repository = "https://github.com/GitoxideLabs/gitoxide"
authors = ["Cameron Esfahani <cesfahani@gmail.com>", "Sebastian Thiel <sebastian.thiel@icloud.com>"]
license = "MIT OR Apache-2.0"
description = "Verifies the connectivity and validity of objects in the database"
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-workspace=true

[lib]
doctest = false

[dependencies]
gix-hash = { workspace=true }
gix-hashtable = { workspace=true }
gix-object = { workspace=true }

[dev-dependencies]
gix-odb = {  }
gix-testtools = { workspace=true }
