lints.workspace = true

[package]
name = "gix-diff"
#workspace=true
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "Calculate differences between various git objects"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-workspace=true
autotests = false

[features]
default = ["blob", "index"]
## Enable diffing of blobs using imara-diff.
blob = ["dep:imara-diff", "dep:gix-filter", "dep:gix-worktree", "dep:gix-path", "dep:gix-fs", "dep:gix-command", "dep:gix-tempfile", "dep:gix-trace", "dep:gix-traverse"]
## Enable diffing of two indices, which also allows for a generic rewrite tracking implementation.
index = ["dep:gix-index", "dep:gix-pathspec", "dep:gix-attributes"]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "gix-hash/serde", "gix-object/serde", "gix-index?/serde"]
## Make it possible to compile to the `wasm32-unknown-unknown` target.
wasm = ["dep:getrandom"]

[lib]
doctest = false

[dependencies]
gix-index = { workspace=true, optional = true }
gix-pathspec = { workspace=true, optional = true }
gix-attributes = { workspace=true, optional = true }
gix-hash = { workspace=true }
gix-object = { workspace=true }
gix-filter = { workspace=true, optional = true }
gix-worktree = { workspace=true, features = ["attributes"], optional = true }
gix-command = { workspace=true, optional = true }
gix-path = { workspace=true, optional = true }
gix-fs = { workspace=true, optional = true }
gix-tempfile = { workspace=true, optional = true }
gix-trace = { workspace=true, optional = true }
gix-traverse = { workspace=true, optional = true }

thiserror = "2.0.17"
imara-diff = { path = "../../imara-diff", version = "0.1.11", optional = true }
serde = { workspace=true, optional = true, features = ["derive"] }
getrandom = { workspace=true, optional = true }   #, features = ["js"]
bstr = { workspace=true }

document-features = { workspace=true, optional = true }

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
